/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
2023-08-28 19:48:19.794782: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-28 19:48:19.954298: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package tagsets to /root/nltk_data...
[nltk_data]   Package tagsets is already up-to-date!
/usr/local/lib/python3.8/dist-packages/code_rationales/grammars
**********Tagging rationals for exp: 0**********
**********Aggregrating rationals for exp: 0**********
r-0
r-1
r-2
r-3
r-4
r-5
r-6
r-7
r-8
r-9
r-10
r-11
r-12
r-13
r-14
r-15
r-16
r-17
r-18
r-19
r-20
r-21
r-22
r-23
r-24
r-25
r-26
r-27
r-28
r-29
r-30
r-31
r-32
r-33
r-34
r-35
r-36
r-37
r-38
r-39
r-40
r-41
r-42
r-43
r-44
r-45
r-46
r-47
r-48
r-49
r-50
r-51
r-52
r-53
r-54
r-55
r-56
r-57
r-58
r-59
r-60
r-61
r-62
r-63
r-64
r-65
r-66
r-67
r-68
r-69
r-70
r-71
r-72
r-73
r-74
r-75
r-76
r-77
r-78
r-79
r-80
r-81
r-82
r-83
r-84
r-85
r-86
r-87
r-88
r-89
r-90
r-91
r-92
r-93
r-94
r-95
r-96
r-97
r-98
r-99
Traceback (most recent call last):
  File "mtrand.pyx", line 899, in numpy.random.mtrand.RandomState.choice
TypeError: 'dict' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/code-rationales/scripts/global_aggregates/global_aggregation.py", line 407, in <module>
    bootstrap_samples_global_results(global_taxonomy_results, params['bootstrapping'])
  File "/workspaces/code-rationales/scripts/global_aggregates/global_aggregation.py", line 377, in bootstrap_samples_global_results
    global_results[exp_id][target_type][source_type] = bootstrapping(source_value, np.mean, size).tolist()
  File "/workspaces/code-rationales/scripts/global_aggregates/global_aggregation.py", line 364, in bootstrapping
    bootstrap_repl = [ np_func( np.random.choice( np_data, size=len(np_data) ) ) for i in range( size ) ]
  File "/workspaces/code-rationales/scripts/global_aggregates/global_aggregation.py", line 364, in <listcomp>
    bootstrap_repl = [ np_func( np.random.choice( np_data, size=len(np_data) ) ) for i in range( size ) ]
  File "mtrand.pyx", line 901, in numpy.random.mtrand.RandomState.choice
ValueError: a must be 1-dimensional or an integer
